# Generated by Django 5.0.6 on 2024-06-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='music/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='music/')),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=500, null=True)),
                ('music_type', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
