# Generated by Django 5.0.6 on 2024-06-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonatedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('order_id', models.CharField(blank=True, max_length=1500, null=True)),
                ('txn_id', models.CharField(blank=True, max_length=1500, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=1500, null=True)),
                ('name', models.CharField(blank=True, max_length=1500, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('amount', models.CharField(blank=True, max_length=500, null=True)),
                ('paid_amount', models.CharField(blank=True, max_length=500, null=True)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('pan_card', models.FileField(blank=True, null=True, upload_to='pancards')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
