# Generated by Django 5.0.6 on 2024-06-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertestimonial',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
