# Generated by Django 5.0.6 on 2024-06-28 16:49

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Timestamp')),
                ('article_main_image', models.ImageField(blank=True, null=True, upload_to='Article/')),
                ('publish', models.BooleanField(default=False)),
                ('activity_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Add Article',
            },
        ),
    ]
