# Generated by Django 5.0.6 on 2024-06-28 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomments',
            options={'verbose_name_plural': 'Blog Comments'},
        ),
    ]
