# Generated by Django 5.0.6 on 2024-06-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcounsellor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='counsellor/'),
        ),
    ]
