# Generated by Django 5.0.6 on 2024-06-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0002_addcounsellor_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expertcategory',
            options={'verbose_name_plural': 'Expert Categories'},
        ),
    ]
