# Generated by Django 5.0.6 on 2024-06-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helplines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addhelpline',
            name='location',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='addhelpline',
            name='timings',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='addhelpline',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='helplines/'),
        ),
    ]
