from django.urls import path, include
from .views import *
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('article_details/<str:id>', article_details, name='article_details'),
    path('blog_details/<str:id>', blog_details, name='blog_details'),
    path('add_contact', add_contact, name='add_contact'),
    path('submit_form', submit_form, name='submit_form'),
    path('submit_form2', submit_form2, name='submit_form2'),
    path('submit_form3', submit_form3, name='submit_form3'),
    path('get_counsellor_data', get_counsellor_data, name="get_counsellor_data"),
    path('get_counsellor/<str:id>', get_counsellor, name="get_counsellor"),
    path('counsellors_list', counsellors_list, name="counsellors_list"),
    path('add_donation', add_donation, name='add_donation'),
    path('webhook_razorpay', webhook_razorpay, name='webhook_razorpay'),

    path('payment', payment, name='payment'),
    path('payment_success', payment_success, name='payment_success'),
    path('payment_cancel', payment_cancel, name='payment_cancel'),
    path('initiate_payment', initiate_payment, name='initiate_payment'),
    path('get_helpline_data', get_helpline_data, name="get_helpline_data"),

    path('', home, name='home'),
    path('about', about, name='about'),
    path('search_result', search_result, name='search_result'),
    path('get_category_data', get_category_data, name='get_category_data'),
    path('glossary', glossary, name='glossary'),
    path('dashboard', dashboard, name='dashboard'),
    path('helplines', helplines, name='helplines'),
    path('add_user', add_user, name='add_user'),
    path('activities', activities, name='activities'),
    path('donations', donations, name='donations'),
    path('counsellors', counsellors, name='counsellors'),
    path('alternate_therapist', alternate_therapist, name='alternate_therapist'),
    path('mindful_articles', mindful_articles, name='mindful_articles'),
    path('counsellors/<str:paginate>', counsellors, name='counsellors'),
    path('articles/<str:paginate>', articles, name='articles'),
    path('verify_account/<str:id>', verify_account, name='verify_account'),
    path('signup', signup, name='signup'),
    path('add_new_user', add_new_user, name='add_new_user'),
    path('contact', contact, name='contact'),
    path('contactus', contactus, name='contactus'),
    path('user_support', user_support, name='user_support'),
    path('professional', professional, name='professional'),
    path('volunteer', volunteer, name='volunteer'),
    path('breathing', breathing, name='breathing'),
    path('music', music, name='music'),
    path('login_user', login_user, name='login_user'),
    path('music_class', music_class, name='music_class'),
    path('smoothing_sound', smoothing_sound, name='smoothing_sound'),
    path('smoothing_sound/<str:id>', smoothing_sound, name='smoothing_sound'),
    path('art', art, name='art'),
    path('login2', login2, name='login2'),
    path('user_login', user_login, name='user_login'),
    path('check_user', check_user, name='check_user'),
    path('guided_meditation', guided_meditation, name='guided_meditation'),
    path('postural', postural, name='postural'),
    path('sound_nature', sound_nature, name='sound_nature'),
    path('dance_class', dance_class, name='dance_class'),
    path('failed2', failed2, name='failed2'),
    path('articles', articles, name='articles'),
    path('chants', chants, name='chants'),
    path('music_article', music_article, name='music_article'),
    path('privacy_policy', privacy_policy, name='privacy_policy'),
    path('terms_conditions', terms_conditions, name='terms_conditions'),
    path('refund', refund, name='refund'),
    path('register', register, name='register'),
    path('blog', blog, name='blog'),
    path('profile', profile, name='profile'),
    path('logout2', logout2, name='logout2'),
    path('user_blog', user_blog, name='user_blog'),
    path('add_user_blog', add_user_blog, name='add_user_blog'),
    path('instrumental', instrumental, name='instrumental'),
    path('delete_blog/<str:id>', delete_blog, name='delete_blog'),
    path('sound_nature/<str:id>', sound_nature, name='sound_nature'),

    path('user_support', user_support, name='user_support'),
    path('add_new_ticket', add_new_ticket, name='add_new_ticket'),
    path('view_qcomments/<str:id>', view_qcomments, name="view_qcomments"),
    path('delete_query/<str:id>', delete_query, name="delete_query"),
    path('add_qcomments', add_qcomments, name="add_qcomments"),
    path('close_ticket', close_ticket, name="close_ticket"),
    path('auth/<int:token>', auth, name="auth"),
    path('verify', verify, name="verify"),
    path('forgot_password', forgot_password, name="forgot_password"),
    path('password_reset_confirm/<str:id>', password_reset_confirm, name="password_reset_confirm"),
    path('forgot', auth_views.PasswordResetView.as_view(template_name='web/forgot_password.html',
                                                        form_class=EmailValidationOnForgotPassword)),
    path('password-reset/', CustomPasswordResetView.as_view(), name='password_reset'),

    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='web/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='web/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='web/password_reset_complete.html'),
         name='password_reset_complete'),

    path('music-details/<str:id>', music_details, name="music-details"),
    path('add_testimonial', add_testimonial, name='add_testimonial'),

]
